[build]
  base = "apps/web"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://gridmanager-production.up.railway.app/api/v1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200