[build]
  command = "echo 'Build already done'"
  publish = "apps/web/dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://gridmanager-api.up.railway.app/api/v1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200