[build]
  base = "apps/web"
  command = "echo 'Build already done'"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF apps/web/"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://gridmanager-production.up.railway.app/api/v1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200