[build]
  base = "apps/web"
  publish = "apps/web/dist"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_OPTIONS = "--max-old-space-size=4096"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  environment = { VITE_API_URL = "https://grid-manager-api.railway.app/api/v1" }

[context.deploy-preview]
  environment = { VITE_API_URL = "https://grid-manager-api.railway.app/api/v1" }
